### ISSUE TITLE
Cannot read properties of undefined ...?

### ISSUE THREAD

**Issue by alexdo83** [KayckMatias/zshorts-automatic-shorts-videos-generator#1]
![hepf](https://github.com/KayckMatias/zshorts-automatic-shorts-videos-generator/assets/25850343/825ebe15-5de2-47aa-8800-13554262ad7d)

**Comment by KayckMatias** [comment]
Hi, you populate `"static/videos"` folder with background videos? (minimum 1 is required)

**Comment by alexdo83** [comment]
> Hi, you populate `"static/videos"` folder with background videos? (minimum 1 is required)

![1](https://github.com/KayckMatias/zshorts-automatic-shorts-videos-generator/assets/25850343/7fbbeef5-eb92-406c-95a7-61f6de32d549)

**Comment by alexdo83** [comment]
Where did I go wrong??

**Comment by KayckMatias** [comment]
It seems right, I'll check what it could be, I haven't tested it on Windows yet, I'll test it soon and fix it.

**Comment by KayckMatias** [comment]
Hi @alexdo83, you can try now? I think #2 fixes it :)

**Comment by KayckMatias** [comment]
Fixed #2
