### ISSUE TITLE
I want the video to be longer than 1 minute, where do I need to change it?

### ISSUE THREAD

**Issue by alexdo83** [KayckMatias/zshorts-automatic-shorts-videos-generator#6]
I want the output video to be longer than 60 seconds, how can I change it here?

![image](https://github.com/KayckMatias/zshorts-automatic-shorts-videos-generator/assets/25850343/e7f1f139-0a88-4714-89c8-c38dd6c0e8a2)

**Comment by KayckMatias** [comment]
In .env
Change LIMIT_SHORT_60_SECONDS to false

**Comment by alexdo83** [comment]
> Trong .env Thay đổi LIMIT_SHORT_60_SECONDS thành false

thanks.
