### ISSUE TITLE
The `punycode` module is deprecated.

### ISSUE THREAD

**Issue by merolaika** [KayckMatias/zshorts-automatic-shorts-videos-generator#7]
npm run generate

`
> zshorts@0.0.1 generate
> node index.js

[INFO] - 2024-01-21 15:35:10: ------------ STARTING NEW SHORT ------------

(node:28776) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[ERROR] - 2024-01-21 15:35:10: No videos available to make shorts, aborting...

C:\Python\zshorts-automatic-shorts-videos-generator\src\services\ffmpeg.js:151
      resolve(metadata.format.duration);
                       ^

TypeError: Cannot read properties of undefined (reading 'format')
    at C:\Python\zshorts-automatic-shorts-videos-generator\src\services\ffmpeg.js:151:24
    at handleCallback (C:\Python\zshorts-automatic-shorts-videos-generator\node_modules\fluent-ffmpeg\lib\ffprobe.js:106:9)
    at handleExit (C:\Python\zshorts-automatic-shorts-videos-generator\node_modules\fluent-ffmpeg\lib\ffprobe.js:190:20)
    at ChildProcess.<anonymous> (C:\Python\zshorts-automatic-shorts-videos-generator\node_modules\fluent-ffmpeg\lib\ffprobe.js:233:11)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
`

Node.js v21.5.0

**Comment by KayckMatias** [comment]
You should put background videos in before generate shorts, please check here:
https://github.com/KayckMatias/zshorts-automatic-shorts-videos-generator?tab=readme-ov-file#configuration


and, I updated the punycode module too, thanks :)

**Comment by KayckMatias** [comment]
This error occurs because you have not placed the background videos in the folder, please check here:
https://github.com/KayckMatias/zshorts-automatic-shorts-videos-generator?tab=readme-ov-file#configuration

and, I updated the punycode module too, thanks :)

**Comment by merolaika** [comment]
Thanks
